title: einkGuides
description: Accumulated eink device knowledge
theme: just-the-docs

url: https://www.eink-guides.info

aux_links: # remove if you don't want this link to appear on your pages
  Kindle: https://www.eink-guides.com/kindle.html
  Viwoods AiPaper: https://www.eink-guides.com/viwoods.html

search_enabled: true
nav_enabled: true
heading_anchors: true

last-edit-timestamp: true

gh_edit_link: true
gh_edit_link_test: "Contribute to eink-guides on GitHub."

color_scheme: dark
